### PR TITLE
Formatted both README and Python file

### LINKED ISSUE #1: Improve documentation in README and code

### PR DESCRIPTION
**Pull request by Mg4145**
Fixes  #1 

Will work on it later if time permits.

### CODE REVIEW

**Comment by Thopterulu** [comment]
Nice work :D didn't knew about this usage of f-strings thank you for showing me that! The only thing I'm unsure of, is the choice of removing the empty line at the end of files, there's a convention ?

**Review by Thopterulu — APPROVED** [review]

**Comment by Mg4145** [comment]
I removed the new lines at the end of files because that's what the python linters recommend. If you run your code with flake8 or pylint with a newline at the end of your file you can see that it doesn't like it. Take for example this file called: 
```test.py```

Which contains: 

```python 
""" Docstring """


def main():
    print("Hello World")


if __name__ == "__main__":
    main()

```

Running pylint

```bash 
$ pylint tst.py
```

Yields the following output:

```bash 
************* Module test
test.py:10:0: C0305: Trailing newlines (trailing-newlines)
test.py:4:0: C0116: Missing function or method docstring (missing-function-docstring)

-----------------------------------
Your code has been rated at 5.00/10
```

A similar complaint can be seen when running it with ```flake8```

```bash 
flake8 test.py
```
Output:
```bash 
test.py:10:1: W391 blank line at end of file
test.py:11:1: BLK100 Black would make changes.
```

Hence, I followed the suggestions to be as close as possible to a style guide. 

If you want your python file to be autoformatted so that it can follow a style guide you can install an autoformatter 
like ```black``` through pip. Here is the [PyPi Documentation](https://pypi.org/project/black/) on how to install and use it.

Hope this helps!

**Comment by Thopterulu** [comment]
It does helps! Thank you for your contribution, do you want me to merge it now?

**Comment by Mg4145** [comment]
Yeah! Merge it! I haven't had much time to look at the code but I will see if I can later.

**Pull request merged**
